name: Lint

on:
  push:

env:
  TERRAFORM_VERSION: "1.5.7"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linting:
    name: Lint Terraform files

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform format
        run: terraform fmt -recursive -check

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configurations
        run: terraform validate -no-color

      - name: Run tfsec linter
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Run checkov linter
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: .checkov.yml
