# Configuration details can be found here:
# https://github.com/nimblehq/publish-github-wiki-action
name: Publish Wiki

on:
  pull_request:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop

jobs:
  publish:
    name: Publish Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Publish Github Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: .github/wiki
